# docker build -t mbwali/bash:rootless -f Dockerfile_bash .

FROM bash

# Create a group and user
RUN addgroup -g 1000 bashuser && \
    adduser -u 1000 -G bashuser -h /home/bashuser -D bashuser

USER 1000

CMD ["bash"]