
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-push-run-
spec:
  pipelineRef:
    name: clone-build-push
  podTemplate:
    # securityContext:
    # # # #   # capabilities:
    # # # #   #   drop:
    # # # #   #   - ALL
    # # #   # # readOnlyRootFilesystem: true
    #   runAsNonRoot: true
    #   runAsUser: 1000
    #   runAsGroup: 1000
    # #   # readOnlyRootFilesystem: true
    # #   # allowPrivilegeEscalation: false
    # #   fsGroup: 65532
    #   runAsUser: 1000

  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        # storageClassName: openebs-hostpath    # change accordingly
  # - name: docker-credentials
  #   secret:
  #     secretName: docker-credentials
  params:
  - name: repo-url
    value: https://github.com/AustrianDataLAB/pacman
  - name: image-reference # registry name
    value: mbwali/testing:latest #registry:5000/testbuild