# https://github.com/kesselborn/tekton-test/blob/master/psp.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:tekton
rules:
  - apiGroups:
      - policy
    resourceNames:
      - system-unrestricted-psp
    resources:
      - podsecuritypolicies
    verbs:
      - use

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:tekton
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:tekton
subjects:
  - kind: ServiceAccount
    name: default
  - kind: ServiceAccount
    name: helm-pipeline-run-sa
